# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dire_actual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion Actual')),
                ('de_quien', models.CharField(blank=True, max_length=50, null=True, verbose_name='De quien es esta direccion?')),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('talla', models.IntegerField(blank=True, null=True)),
                ('IMC', models.IntegerField(blank=True, null=True)),
                ('cirugia_mamaria', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, null=True, verbose_name='Cirugias Mamarias')),
                ('otras_cirugias', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, null=True, verbose_name='Otras Cirugias')),
                ('antecedentes', models.CharField(blank=True, choices=[('CAM', 'Ca de Mama'), ('CAO', 'Ca de Ovario'), ('Otro', 'Otro Ca')], default='Otro', max_length=8, null=True, verbose_name='Antecedentes de Cancer')),
                ('atec_rt', models.CharField(blank=True, choices=[('T', 'Toracica'), ('G', 'Ginecologica'), ('O', 'Otro')], max_length=5, null=True, verbose_name='Atec de RT')),
                ('ante_fam', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, null=True, verbose_name='Hay antecedentes familiares?')),
                ('cancer_mama', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Cancer de mama')),
                ('cancer_ovario', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Cancer de ovario')),
                ('cancer_prostata', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Cancer de prostata')),
                ('cancer_colon', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Cancer de colon')),
                ('cancer_otro', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Otro cancer')),
                ('candetalles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalles')),
                ('hijos', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('edad_primero', models.IntegerField(blank=True, null=True, verbose_name='Edad del Primero?')),
                ('amamanto', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Amamanto?')),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('anticonceptivos', models.CharField(choices=[('S', 'SI'), ('N', 'NO'), ('A', 'ACO'), ('I', 'IM')], default='N', max_length=3)),
                ('tiempo_anti', models.IntegerField(blank=True, null=True, verbose_name='Tiempo')),
                ('menopausia', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=5, verbose_name='Menopausia')),
                ('edad_meno', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('anos_repro', models.CharField(blank=True, max_length=50, null=True, verbose_name='A\xf1os reproductivos')),
                ('trh', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=5, verbose_name='THR')),
                ('trh_opciones', models.CharField(blank=True, choices=[('V.O', 'Via Oral'), ('G', 'Gel'), ('I', 'Intramuscular'), ('O', 'Otros'), ('NO', 'Ninguno')], default='NO', max_length=5, null=True, verbose_name='Opciones')),
                ('abortos', models.CharField(choices=[('PRO', 'Provocados'), ('PER', 'Perdida'), ('NO', 'Ninguno')], default='NO', max_length=5, verbose_name='Abortos')),
                ('cuantos_abortos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuantos?')),
                ('primera_gesta', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=5, verbose_name='Primera gesta?')),
                ('edad_gestacional', models.IntegerField(blank=True, null=True, verbose_name='Edad gestacional')),
            ],
            options={
                'verbose_name': 'Ficha de Recoleccion de Datos',
                'verbose_name_plural': 'Ficha de Recoleccion de Datos',
            },
        ),
        migrations.CreateModel(
            name='Mamografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamoDespi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamografia despistaje')),
                ('mamoDiag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamografia Diagnostica')),
                ('nodulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nodulo')),
                ('antecedentes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antecedentes familiares')),
                ('otros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros factores de riesgo')),
                ('densidad', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=3, null=True, verbose_name='Densidad')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('birads', models.CharField(choices=[('0', 'Estudio insuficiente - Se recomienda'), ('1', 'Normal'), ('2', 'Anormal,Benigno'), ('3', 'Anormal, probablemente benigno'), ('4a', 'Anormal, probablemente benigno (baja)'), ('4b', 'Anormal, probablemente benigno(intermedia) '), ('4c', 'Anormal, probablemente benigno(alta)'), ('5', 'Anormal, maligno'), ('6', 'Anorma, maligno ya biopsiado')], max_length=3, null=True, verbose_name='BIRADS')),
                ('eg', models.CharField(max_length=100, null=True, verbose_name='EG')),
                ('hallazgos', models.CharField(max_length=100, null=True, verbose_name='Hallazgos?, si o no y descripcion')),
                ('des_birads', models.CharField(max_length=150, null=True, verbose_name='Birads')),
                ('mamas', models.CharField(blank=True, choices=[('PoM', 'Pequenas o Moderadas'), ('Vol', 'Voluminosas')], max_length=5, null=True, verbose_name='Mamas')),
                ('consistencia', models.CharField(blank=True, choices=[('Bl', 'Blandas o faciles de Examinar'), ('Int', 'Intermedio'), ('F/MF', 'Firmes/Muy Firmes')], max_length=5, null=True, verbose_name='Consistencia')),
                ('hallazgo_si', models.CharField(blank=True, choices=[('NO', 'NO'), ('Nod', 'Nodulo o Tumor'), ('Mas', 'Masa mal definida'), ('Sec', 'Secrecion'), ('O', 'Otros')], max_length=5, null=True, verbose_name='Hallazgo')),
            ],
            options={
                'verbose_name': 'Mamografia',
                'verbose_name_plural': 'Mamografias',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno')),
                ('del_marido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido del Marido')),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=3)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('AEM', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Sabes lo que es?')),
                ('loHace', models.CharField(choices=[('R', 'REGULARMENTE'), ('A', 'A veces'), ('NU', 'NUNCA')], default='NU', max_length=3, verbose_name='Lo haces?')),
                ('bulto_pecho', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('NS', 'No se')], default='N', max_length=3, verbose_name='Alguna vez sentiste un bulto en el pecho?')),
                ('problema_mama', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez consultaste por un problema de la mama?')),
                ('mama_detalle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cual')),
                ('hizo_mamo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez te hiciste Mamografia?')),
                ('eco_mama', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez te hiciste una ecografia mamaria?')),
                ('cancer_mama', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguien en la familia alguna vez tuvo cancer de mama?')),
                ('tenido_cancer', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Conoces a alguien que haya tenido cancer de mama?')),
            ],
            options={
                'verbose_name': 'Ficha de Paciente',
                'verbose_name_plural': 'Ficha de Pacientes',
            },
        ),
        migrations.DeleteModel(
            name='Registrado',
        ),
        migrations.AddField(
            model_name='mamografia',
            name='registrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Persona'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='registrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Persona'),
        ),
    ]
