# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20170510_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='detalles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='detalles'),
        ),
        migrations.AddField(
            model_name='mamografia',
            name='descripcio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='ante_fam',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Hay antecedentes familiares?'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='antecedentes',
            field=models.CharField(choices=[('N', 'No'), ('CAM', 'Ca de Mama'), ('CAO', 'Ca de Ovario'), ('Otro', 'Otro Ca')], default='N', max_length=8, verbose_name='Antecedentes de Cancer'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='atec_rt',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('T', 'Toracica'), ('G', 'Ginecologica'), ('O', 'Otro')], default=False, max_length=5, null=True, verbose_name='Atec de RT'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cirugia_mamaria',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Cirugias Mamarias'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='otras_cirugias',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Otras Cirugias'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='birads',
            field=models.CharField(blank=True, choices=[('0', 'Estudio insuficiente - Se recomienda'), ('1', 'Normal'), ('2', 'Anormal,Benigno'), ('3', 'Anormal, probablemente benigno'), ('4a', 'Anormal, probablemente benigno (baja)'), ('4b', 'Anormal, probablemente benigno(intermedia) '), ('4c', 'Anormal, probablemente benigno(alta)'), ('5', 'Anormal, maligno'), ('6', 'Anorma, maligno ya biopsiado')], max_length=3, null=True, verbose_name='BIRADS'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='densidad',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=3, null=True, verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='des_birads',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Birads'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='eg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EG'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='hallazgos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hallazgos?, si o no y descripcion'),
        ),
    ]
