# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20170614_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='tipo_aborto',
            field=models.CharField(choices=[('PRO', 'Provocados'), ('PER', 'Perdida')], default=None, max_length=10, verbose_name=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mamografia',
            name='antecedentes1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antecedentes familiares'),
        ),
        migrations.AddField(
            model_name='mamografia',
            name='cero',
            field=models.CharField(default=None, max_length=100, verbose_name='0:Estudio insuficiente - Se recomienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mamografia',
            name='otros1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros factores de riesgo'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='abortos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=5, verbose_name='Abortos'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='amamanto',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Amamant\xf3?'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='antecedentes',
            field=models.CharField(choices=[('N', 'No'), ('CAM', 'Ca de Mama'), ('CAO', 'Ca de Ovario'), ('Otro', 'Otro Ca')], default='N', max_length=8, verbose_name='Antecedentes de C\xe1ncer'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='anticonceptivos',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO'), ('A', 'ACO'), ('I', 'IM')], default='N', max_length=3, verbose_name='Anticonceptivos Hormonales'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cancer_colon',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='C\xe1ncer de colon'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cancer_mama',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='C\xe1ncer de mama'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cancer_otro',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Otro C\xe1ncer'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cancer_ovario',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='C\xe1ncer de ovario'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cancer_prostata',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='C\xe1ncer de prostata'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cuantos_abortos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cu\xe1ntos?'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='edad_primero',
            field=models.IntegerField(blank=True, null=True, verbose_name='A que Edad se embarazo?'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='trh',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=5, verbose_name='TRH'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='trh_opciones',
            field=models.CharField(choices=[('V.O', 'Via Oral'), ('G', 'Gel'), ('I', 'Intramuscular'), ('O', 'Otros')], default='O', max_length=5, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='antecedentes',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='birads',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4a', '4a'), ('4b', '4b'), ('4c', '4c'), ('5', '5'), ('6', '6')], default=None, max_length=3, verbose_name='BIRADS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='densidad',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default=None, max_length=3, verbose_name='Densidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='otros',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cancer_mama',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguien en la familia alguna vez tuvo C\xe1ncer de mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tenido_cancer',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Conoces a alguien que haya tenido C\xe1ncer de mama?'),
        ),
    ]
