# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20170509_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='cancer_detalles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='trh_opciones',
            field=models.CharField(blank=True, choices=[('V.O', 'Via Oral'), ('G', 'Gel'), ('I', 'Intramuscular'), ('O', 'Otros'), ('NO', 'Ninguno')], default='NO', max_length=5, null=True, verbose_name='Opciones'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='AEM',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Sabes lo que es?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bulto_pecho',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('NS', 'No se')], default='N', max_length=3, verbose_name='Alguna vez sentiste un bulto en el pecho?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cancer_mama',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguien en la familia alguna vez tuvo cancer de mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='eco_mama',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez te hiciste una ecografia mamaria?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hizo_mamo',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez te hiciste Mamografia?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mama_detalle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cual'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='problema_mama',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Alguna vez consultaste por un problema de la mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tenido_cancer',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=3, verbose_name='Conoces a alguien que haya tenido cancer de mama?'),
        ),
    ]
