# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20170511_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='registrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Persona', unique=True),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='registrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Persona', unique=True),
        ),
    ]
