# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20170615_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamografia',
            name='hallazgo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='consistencia',
            field=models.CharField(choices=[('Bl', 'Blandas o faciles de Examinar'), ('Int', 'Intermedio'), ('F/MF', 'Firmes/Muy Firmes')], default=None, max_length=5, verbose_name='Consistencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='descripcio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='eg',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='EG'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='hallazgo_si',
            field=models.CharField(choices=[('NO', 'NO'), ('Nod', 'Nodulo o Tumor'), ('Mas', 'Masa mal definida'), ('Sec', 'Secrecion'), ('O', 'Otros')], default=None, max_length=5, verbose_name='Hallazgo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='hallazgos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default=None, max_length=5, verbose_name='Hallazgos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='mamas',
            field=models.CharField(choices=[('PoM', 'Pequenas o Moderadas'), ('Vol', 'Voluminosas')], default=None, max_length=5, verbose_name='Mamas'),
            preserve_default=False,
        ),
    ]
