# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_auto_20170616_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='IMC',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='estatura',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
