# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_auto_20170616_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='atec_rt',
            field=models.CharField(choices=[('N', 'No'), ('T', 'Tor\xe1cica'), ('G', 'Ginecol\xf3gica'), ('O', 'Otro')], default='O', max_length=5, verbose_name='Atec de RT'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
